#!/usr/bin/env python3

import sys

try:

    sys.path.insert(0, './src')
    from os     import _exit, getpid, kill, unlink
    from time   import sleep
    from signal import signal, SIGTERM, SIGINT, SIGCHLD
    import subprocess
    import PCM
    import Server, Watcher, Engine

except ImportError as e:

    print(str(e), file=sys.stderr)
    print('Cannot find the module(s) listed above. Exiting.', file=sys.stderr)
    sys.exit(1)

if __name__ == '__main__':

    pcm = PCM.PCM('./pcm.cfg', sys.argv)
    server = Server.Server(pcm.configuration, pcm.logger)
    engine = Engine.Engine(pcm.configuration, pcm.logger, 'Engine')
    watcher = Watcher.Watcher(pcm.configuration, pcm.logger, 'Watcher')
    try:
        if sys.argv[1] == 'stop':
            server.stop()
            engine.stop()
            watcher.stop()
        elif sys.argv[1] == 'start':
            p1 = subprocess.Popen([sys.argv[0],'listen'], shell=False)
            p2 = subprocess.Popen([sys.argv[0],'engine'], shell=False)
            p3 = subprocess.Popen([sys.argv[0],'watcher'], shell=False)
        elif sys.argv[1] == 'listen': server.start()
        elif sys.argv[1] == 'engine':
            engine.createSSHClient()
            engine.start()
            engine.run()
        elif sys.argv[1] == 'watcher':
            watcher.start()
            watcher.run()
        elif sys.argv[1] == 'status':
            watcher.status()
            server.status()
            engine.status()


    except (IndexError, FileNotFoundError, NameError) as e: print(str(e), file=sys.stderr)

