#!/usr/bin/env python3

import sys

try:

    sys.path.insert(0, './src')
    from os     import _exit, getpid, kill, unlink
    from time   import sleep
    from signal import signal, SIGTERM, SIGINT, SIGCHLD
    import subprocess
    import PCM
    import Server

except ImportError as e:

    print(str(e), file=sys.stderr)
    print('Cannot find the module(s) listed above. Exiting.', file=sys.stderr)
    sys.exit(1)

if __name__ == '__main__':

    pcm = PCM.PCM('./pcm.cfg', sys.argv)
    server = Server.Server(pcm.configuration, pcm.logger)

    try:
        if sys.argv[1] == 'stop':
            server.stop()
            pcm.stopEngine()
        elif sys.argv[1] == 'start':
            subprocess.Popen([sys.argv[0],'listen'], shell=False)
            print('one')
            subprocess.Popen([sys.argv[0],'engine'], shell=False)
        elif sys.argv[1] == 'listen': server.start()
        elif sys.argv[1] == 'engine': pcm.startEngine()
        elif sys.argv[1] == 'status':
            server.status()
            pcm.engineStatus()


    except (IndexError, FileNotFoundError, NameError) as e: print(str(e), file=sys.stderr)

