#!/usr/bin/env python3

import sys

try:

    sys.path.insert(0, './src')
    from os     import _exit, getpid, kill, unlink
    from time   import sleep
    from signal import signal, SIGTERM, SIGINT, SIGCHLD
    import subprocess
    import PCM

except ImportError as e:

    print(str(e), file=sys.stderr)
    print('Cannot find the module(s) listed above. Exiting.', file=sys.stderr)
    sys.exit(1)

if __name__ == '__main__':

    pcm = PCM.PCM('./pcm.cfg', sys.argv)
    try:
        if sys.argv[1] == 'stop': pcm.server.stop()
        elif sys.argv[1] == 'start': subprocess.Popen([sys.argv[0],'listen'], shell=False)
        elif sys.argv[1] == 'listen': pcm.server.start()

    except (IndexError, FileNotFoundError) as e: print(str(e), file=sys.stderr)
    except NameError: pass
